import type { Metadata } from "next";
import "./globals.css";
import "./sass/layout.scss";
import { outfit } from "./fonts/font";
import { Sidebar } from "./components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className}`}>
        <div className="layout-container">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
